services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    container_name: kaufland_django
    restart: unless-stopped
    volumes:
      - .:/app
      - /home/altera/.ssh:/root/.ssh:ro
      - /srv/kaufland:/srv/kaufland
    env_file:
      - .env.docker
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - kaufland_network
    command: >
      sh -c "python manage.py migrate &&
            uvicorn kaufland_API.asgi:application --host 0.0.0.0 --port 8000 --reload"

  postgres:
    image: postgres:17.1
    restart: unless-stopped
    container_name: kaufland_postgres
    env_file:
      - .env.docker
    ports:
    - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - kaufland_network

  redis:
    image: redis:7
    restart: unless-stopped
    container_name: kaufland_redis
    networks:
      - kaufland_network
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]

  nginx:
    image: nginx:latest
    restart: unless-stopped
    container_name: kaufland_nginx
    ports:
      - "8050:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/app/static
      - media_volume:/app/media
    depends_on:
      django:
        condition: service_started
    networks:
      - kaufland_network

volumes:
  media_volume:
  postgres_data:
  static_files:

networks:
  kaufland_network:
    driver: bridge
