"""
Django settings for kaufland_API project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
from config import (
    POSTGRES_DB,
    POSTGRES_PASSWORD,
    POSTGRES_USER,
    DB_HOST,
    DB_PORT,
    MAIN_HOST,
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-er2a%p#jkp3i$2t-*a!q-i!bkai)mw1se@-=uqxl+cz#%%w(jp"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "django",
    "192.168.0.193",
    "192.168.0.111",
    "kauf.automatonsoft.de",
    "192.168.0.100",
    "192.168.0.134",
    "94.126.201.244",
    "217.11.76.91",
]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:8050",
    "http://localhost:8000",
    "http://127.0.0.1:8050",
    "http://127.0.0.1:8000",
    "http://django:8050",
    "http://django:8000",
    "http://192.168.0.100:8050",
    "http://192.168.0.100:8000",
    "http://192.168.0.111:8050",
    "http://192.168.0.111:8000",
    "http://192.168.0.134:8050",
    "http://192.168.0.134:8000",
    "http://94.126.201.244:8000",
    "http://94.126.201.244:8050",
    "http://217.11.76.91:8000",
    "http://217.11.76.91:8050",
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "adrf",
    "rest_framework",
    "main_api",
    "channels",
    "rest_framework_simplejwt",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

WS_URL = MAIN_HOST

ROOT_URLCONF = "kaufland_API.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "main_api.context_processors.global_settings",  # <--- вот это
            ],
        },
    },
]

WSGI_APPLICATION = "kaufland_API.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": POSTGRES_DB,
        "USER": POSTGRES_USER,
        "PASSWORD": POSTGRES_PASSWORD,
        "HOST": DB_HOST,
        "PORT": DB_PORT,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Etc/GMT-5"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Настройка статических файлов
STATIC_URL = "/static/"

STATICFILES_DIRS = [
    str(BASE_DIR / "static"),
]

STATIC_ROOT = str(BASE_DIR / "staticfiles")  # Для команды collectstatic

# Настройка медиафайлов (для загружаемых файлов)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

ASGI_APPLICATION = "kaufland_API.asgi.application"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_CHARSET": "utf-8",
}

# (не обязательно, но полезно)
CACHE_TTL = 60 * 60 * 24  # сутки

# Использование ВебСокета для общения в реальном времени
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    },
}

# Максимальный размер принимаемых файлов для django
DATA_UPLOAD_MAX_MEMORY_SIZE = 30 * 1024 * 1024  # 30 МБ в байтах

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(weeks=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(weeks=1),
}
